#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = 'kitty'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#5fb3b3'  # Oceanic Next Light Blue
    template = '{{ .Path }}'
    [blocks.segments.properties]
      style = 'full'
  [[blocks.segments]]
    type = "nix-shell"
    style = "plain"
    foreground = "#cdd3de"
    template = "{{if ne .Type \"unknown\"}} <#c0f6fb>nix:(</>shell<#c0f6fb>)</>{{end}}"
  [[blocks.segments]]
    type = "docker"
    style = "plain"
    foreground = "#6699cc"  # Oceanic Next Blue
    template = " <#6699cc>context:(</><#cdd3de>{{ .Context }}</><#6699cc>)</>"

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#ec5f67'  # Oceanic Next Red
    template = ' <#ec5f67>git:(</><#cdd3de>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</><#ec5f67>)</>'
    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#5fb3b3'  # Oceanic Next Light Blue
    template = '{{ .FormattedMs }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "#5fb3b3",  # Oceanic Next Light Blue
    ]
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "#5fb3b3",  # Oceanic Next Light Blue
  ]
  template = '❯ '

[secondary_prompt]
  foreground = '#5fb3b3'  # Oceanic Next Light Blue
  template = '❯❯ '
